# G1 Robot Configuration
robot:
  type: "g1"
  num_joints: 29
  base_height: 0.793
  robot_radius: 0.25
  max_linear_velocity: 0.5
  max_angular_velocity: 0.8

lidar:
  type: "livox_mid360"
  flip: true
  offset:
    x: 0.10
    y: 0.0
    z: 0.60
  max_range: 15.0
  min_range: 0.15
  body_filter_radius: 0.3

network:
  interface: "eth0"
  robot_ip: "192.168.123.161"
  pc_ip: "192.168.123.100"
  lidar_ip: "192.168.123.164"

slam:
  voxel_size: 0.5
  max_range: 15.0
  min_range: 0.3
  enable_loop_closure: true
  keyframe_distance: 1.0
  map_directory: "/home/unitree/maps"

navigation:
  max_vel_x: 0.4
  max_vel_y: 0.2
  max_vel_theta: 0.5
  acc_lim_x: 0.3
  acc_lim_y: 0.2
  inflation_radius: 0.55

web:
  ws_port: 9090
  http_port: 8080
